if: tag IS blank

language: node_js

node_js: 9

cache:
  directories:
    - node_modules

stages:
  - test
  - release

install: npm ci
before_install:
  - dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/.scripts

jobs:
  include:
    - stage: test
      before_script: test-reporter before-build
      after_script: test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: release
      install: npm install --production
      script: npx semantic-release
      if: branch = master
      if: type IN (push)
